column_width = 120
indent_type = 'Spaces'
# indent_type = 'Tabs'
indent_width = 3
quote_style = 'AutoPreferSingle'
no_call_parentheses = true
line_endings = 'Unix'
# call_parentheses = 'NoSingleTable'
call_parentheses = 'NoSingleString'
# call_parentheses = 'Always'
# call_parentheses = 'None'
# collapse_simple_statement = "Always" # This makes some functions be one liners
